#!/usr/bin/bash
PS3=">>"
script_dir=$(dirname "$0") 
select choice in Create_DB List_DB Drop_DB Connect_DB Exit
do
case $choice in 
Create_DB )
	echo "create DB"
	"$script_dir/create_db"
	;;
List_DB ) 
	echo "listing DB"
	"$script_dir/list_db"
	;;
Drop_DB )
        echo "Dropping DB Will Delete ALL the DB DATA! This includes the DB Structure"
        "$script_dir/drop_db" 
        ;;
Connect_DB )
	echo "Connecting DB"
	"$script_dir/connect_db"
	;;
Exit )
	echo "Exiting"
	break
	;;
* )
        echo "Invalid option. Please select again."
esac
done
