#!/usr/bin/bash

db_dir="."  # Use the current directory where the tables reside

echo "The existing tables are: "
tables=($(ls "$db_dir"))

for ((i=0; i<${#tables[@]}; i++)); do
    echo "$((i+1))) ${tables[$i]}"
done

valid_choice=false
while [ "$valid_choice" = false ]; do
    echo "Enter the number of the table you want to view: "
    read table_num

    if ! [[ "$table_num" =~ ^[1-9][0-9]*$ ]] || ((table_num < 1 || table_num > ${#tables[@]})); then
        echo "Invalid choice. Please enter a valid number."
    else
        valid_choice=true
        table_index=$((table_num - 1))
        table_to_view="${tables[$table_index]}"

        echo "Viewing table: $table_to_view"
        table_path="$db_dir/$table_to_view"

        echo "Enter the row number you want to view: "
        read row_num

        # Display the specified row
        sed -n "${row_num}p" "$table_path"
    fi
done

